name: Create Issue on Repository Creation

on:
  repository:
    types: [created]

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create Issue
        uses: actions/github-script@0.11.0
        with:
          script: |
            const github = context.github;
            const { owner, repo } = context.repo;

            const issueTitle = 'Welcome to the Repository!';
            const issueBody = `Thank you for creating the repository ${repo}. We hope you find it useful!`;

            await github.issues.create({
              owner,
              repo,
              title: issueTitle,
              body: issueBody
            });
